POST  http://localhost:8080/clients
Content-Type: application/json


{
  "firstName": "Chu",
  "lastName": "Li",
  "birthDay": "10-10-2010",
  "email": "li@gmail.ru",
  "phone": "+375291001020",
  "passport_id": {
    "seriesAndNumber": "MR223456",
    "registrationDate": "08-01-2000"
  },
  "address_id": {
    "city": "Minsk",
    "street": "Zaharova",
    "home": 8,
    "flat": 19
  },
  "drivingExperience": "5"
}


###

GET  http://localhost:8080/clients/2
Content-Type: application/json

###



GET  http://localhost:8080/clients
Content-Type: application/xml

###
GET  http://localhost:8080/clients
Content-Type: application/json

###




PUT  http://localhost:8080/clients/{phone}
Content-Type: application/json

{
  "id": "1",
  "phone": "+375291001010"
}


###